import { KeyBlueButton } from "buttons";
import { FormattedMessage as T } from "react-intl";
import { SeedCopyConfirmModal } from "modals";
import { Tooltip } from "shared";
import { LoaderBarBottom } from "indicators";
import "style/CreateWalletForm.less";

const CreateWallet = ({
  mnemonic,
  createWalletConfirmNewSeed,
  handleCopySeed,
  showCopySeedConfirm,
  onCancelCopySeedConfirm,
  onSubmitCopySeedConfirm,
  onReturnToExistingOrNewScreen,
  getCurrentBlockCount,
  getNeededBlocks,
  getEstimatedTimeLeft,
  getDaemonSynced,
}) => (
  <Aux>
    <div className="getstarted content">
      <Tooltip text={ <T id="createWallet.goBack" m="Go back" /> }><div className="go-back-screen-button" onClick={onReturnToExistingOrNewScreen}/></Tooltip>
      <div className="content-title">
        <T id="createWallet.title" m={"Create a new wallet"}/>
      </div>
      <div className="content-text">
        <div className="column">
          <p>
            <T id="createWallet.info" m={`
              Wallets are determinstically generated by a wallet seed. The seed is
              a master key of your wallet and the entire wallet can be recreated at
              any time using it. If the wallet encryption passphrase is forgotten
              or the wallet is destroyed, the seed can be used to recover the wallet.`} />
            <span className="bold">
              <T id="creteWallet.writeSeedReminder" m="Write down the following seed and save it in a secure location."/>
            </span>
          </p>
          <p>
            <T id="createWallet.nextPromptSeed" m="The next prompt will require entering this seed to confirm it has been saved."/>
          </p>
        </div>
        <div className="column">
          <p>
            <T id="createWallet.lossInfo" m={"To help avoid permanent loss of your wallet, the seed must be backed up before continuing."} />
          </p>
          <p>
            <T id="createWallet.lossInfo2" m={`{warningNotice}  Failure to keep this seed private can result in the theft of your entire wallet. Under no circumstances should this seed ever be revealed to someone else.
              `}
            values={{
              warningNotice: <span className="orange"><T id="createWallet.warningNotice" m="Warning:"/></span>
            }}
            />
          </p>
        </div>
      </div>
      <div className="seedArea">
        {mnemonic.split(" ").map((word, i) => {
          return (
            <div key={i} className="seedWord">
              {word}
            </div>
          );
        })}
        <div className="copy">
          <Tooltip text={ <T id="createWallet.copy" m="Copy Seed" /> }><a className="copy-to-clipboard-icon" onClick={handleCopySeed}/></Tooltip>
        </div>
      </div>
      <div className="toolbar">
        <KeyBlueButton className="wallet-key-blue-button" onClick={createWalletConfirmNewSeed}>
          <T id="createWallet.continueBtn" m="Continue" />
        </KeyBlueButton>
      </div>
      <LoaderBarBottom  {...{ getCurrentBlockCount, getNeededBlocks, getEstimatedTimeLeft, getDaemonSynced }}  />
    </div>
    <SeedCopyConfirmModal
      show={showCopySeedConfirm}
      onSubmit={onSubmitCopySeedConfirm}
      onCancelModal={onCancelCopySeedConfirm}
    />
  </Aux>
);

export default CreateWallet;
