const darkTheme = {
  "background-back-color": "#223767",
  "background-container": "#1B2B54",
  "background-container-opaque": "rgba(54, 87, 158, 0.895)",
  "background-container-hover": "#1B2B54",
  "background-hovered": "#29417A",
  "input-color-default": "#E9F8FE",
  "input-color-hovered": "#E9F8FE",
  "input-color-focused": "#E9F8FE",
  "input-color-disabled": "#dadfe2",
  "input-color-shadow": "rgba(9, 20, 64, 0.21)",
  "button-text": "#2F4D8C",
  "white-button-text": "#E9F8FE",
  "title-text-and-button-background": "#B7DEEE",
  "title-text-and-button-background-hovered": "#608ACE",
  "title-text-and-button-background-drop-shadow": "rgba(181, 187, 197, 0.34)",
  "stroke-color-default": "#769ECF",
  "stroke-color-hovered": "#B7DEEE",
  "stroke-color-focused": "#a9c5ff",
  "input-color": "#2970ff",
  "input-color-blue-shadow": "rgba(41, 112, 255, 0.21)",
  "input-color-hover": "#7ea9ff",
  "account-button-hover": "#4a92ff",
  "link-color": "#2970FF",
  "link-hover-color": "#6397ff",
  "accent-color": "#2ed8a3",
  "blue-highlight-background": "#2F4D8C",
  "tab-text": "#608ACE",
  "tab-text-active-hover": "#E9F8FE",
  "cyan-bold": "#69d5f7",
  "disabled-color": "#3C62B0",
  "disabled-background-color": "#1F325F",
  "disabled-background-color-lighter": "#2F4D8C",
  "success-text-color": "#41be53",
  "error-text-color": "#fd714b",
  "error-red": "#ED6D47",
  "error-red-hover": "red",
  "vote-yes-color": "#2ed8a3",
  "vote-no-color": "#f2734f",
  "vote-abstain-color": "#596d81",
  "white-border": "#1B2B54",
  "display-wallet-gradient-right": "#a9a9aa",
  "display-wallet-gradient-selected-right": "#6ed3f3",
  "tx-history-background-hover": "#29417A",
  "sidebar-color": "#152042",
  "short-separator-border": "#36579E",
  "sidebar-bottom-light-text-color": "#7DA7D9",
  "header-desc-color": "#769ECF",
  "sidebar-menu-link": "#6F98D3",
  "linear-progress-text": "#1B2B54",
  "wallet-label": "#3C62B0",
  "new_wallet-label": "#769ECF",
  "selected_wallet-label": "#091440",
  "wallet-desc": "#25549F",
  "getstarted-menu-color": "#B7DEEE",
  "tutorial-header": "#B7DEEE",
  "step-indicator": "#3C62B0",
  "combobox-outer-bottom-border": "#223767",
  "combobox-restore-border": "#769ECF",
  "text-toggle-button-active-bg": "#29417A",
  "text-toggle-button-active-text": "#E9F8FE",
  "text-toggle-button-border": "#1B2B54",
  "text-toggle-button-bg": "#1F325F",
  "text-toggle-button-inactive-text": "#2F4D8C",
  "header-desc-lighter-color": "#99C1E3",
  "info-modal-button-bg": "#7DA7D9",
  "info-modal-button-text": "#0E152F",
  "agenda-card-bottom-cfg": "#99C1E3",
  "tabbed-page-header-bg": "#223767",
  "tabbed-page-header-active-bg": "#2F4D8C",
  "tabbed-page-header-text": "#E9F8FE",
  "overview-balance-label": "#769ECF",
  "chart-axis-stroke": "#1B2B54",
  "chart-axis-text": "#769ECF",
  "disabled-background-color-dark": "#152042",
  "wallet-tutorial-text": "#E9F8FE",
  "wallet-tutorial-link": "#608ACE",
  "wallet-tutorial-step-indicator": "#99C1E3",
  "modal-text": "#99C1E3",
  "modal-bottom": "#E9F8FE",
  "modal-stroke-color": "#1B2B54",
  "settings-desc": "#769ECF",
  "wallet-close-button-bg": "#1B2B54",
  "wallet-close-button-text": "#E9F8FE",
  "select-stroke-color": "#608ACE",
  "select-placeholder": "#608ACE",
  "account-text": "#3C62B0",
  "account-pubkey-text": "#2970FF",
  "back-button-bg": "#1B2B54",
  "back-button-text": "#E9F8FE",
  "back-button-dark-text": "#0E152F",
  "tx-detail-text": "#E9F8FE",
  "tx-detail-raw-shadow":
    "linear-gradient(to top, rgb(243, 246, 246, 0.25) 10%, rgb(243, 246, 246, 0.20) 20%, rgb(243, 246, 246, 0) 70%)",
  "home-content-link": "#99C1E3",
  "transfer-details-bg": "#152042",
  "filter-menu-arrow": "#99C1E3",
  "filter-menu-bg-hover": "#3C62B0",
  "menutab-hover": "#7DA7D9",
  "tooltip-container": "#1F325F",
  "loader-bg": "#223767",
  "display-wallet-bg": "#152042",
  "select-border": "#608ACE",
  "toggle-switch-bg": "#7DA7D9",
  "toggle-switch-knob-bg": "#E9F8FE",
  "transaction-account-name-bg": "#2F4D8C",
  "account-row-hover": "#1F325F",
  "chart-cursor-color": "#36579E",
  "linear-progress-text-default": "#fff",
  "linear-progress-text-initial": "#7DA7D9",
  "onboard-toolbar-shadow": "rgba(9,20,64,0.13)",
  "onboard-toolbar-background": "#152042",
  "background-copy-color": "#e9f8ff",
  "input-placeholder-color": "#608ACE",
  "seedword-number-color": "#223767",
  "seedword-select-border-default-text-color": "#7DA7D9",
  "seedword-select-border-default-border-color": "#2F4D8C",
  "seedword-select-border-default-hover-border-color": "#608ACE",
  "seedword-select-border-default-hover-text-color": "#7DA7D9",
  "txdetails-top-bg": "#1F325F",
  "trezor-line-color": "#608ACE",
  "proposal-text-markdown": "#f6f8fa",
  "background-address-copy-color": "#2F4D8C",
  "icons-shadow": "#09144036",
  "no-more-tickets-indicator-bg": "#2F4D8C",
  "input-copy-hover-color": "#78d9f8",
  "coinjoin-sum-color": "#7DA7D9",
  "coinjoin-sum-text-color": "#fff",
  "privacy-balance-color": "#b7deee",
  "privacy-balance-label-color": "#b7deee",
  "privacy-balance-mixed-label-color": "#b7deee",
  "privacy-mixer-status-color": "#b7deee",
  "mixer-settings-label": "#e9f8fe",
  "mixer-settings-disabled": "#3c62b0",

  // override pi-ui's toggle default dark background
  "toggle-bar-color": "var(--background-copy-color)",

  // override pi-ui's tab colors
  "tab-default-color": "transparent", // default border
  "tab-active-background": "var(--background-back-color)",
  "tab-text-active-color": "var(--input-color-default)",
  "tab-text-color": "var(--sidebar-menu-link)",

  /* icons */
  "menu-settings": "url('style/icons/menuSettingsDark.svg')",
  "menu-accounts": "url('style/icons/accountsActiveDark.svg')",
  "menu-governance": "url('style/icons/governanceActiveDark.svg')",
  "menu-transactions": "url('style/icons/transactionsActiveDark.svg')",
  "menu-overview": "url('style/icons/overviewActiveDark.svg')",
  "menu-privacy": "url('style/icons/privacyDark.svg')",
  "menu-tickets": "url('style/icons/ticketsActiveDark.svg')",
  "menu-ln": "url('style/icons/lightningDark.svg')",
  "menu-trezor": "url('style/icons/trezorActiveDark.svg')",
  "menu-hamburger": "url('style/icons/hamburgerDark.svg')",
  "menu-arrow": "url('style/icons/arrowDark.svg')",
  "menu-mixer-icon": "url('style/icons/menuMixerDark.svg')",
  "menu-spvon-icon": "url('style/icons/menuSpvOnDark.svg')",
  "menu-spvoff-icon": "url('style/icons/menuSpvOffDark.svg')",
  "menu-block-synced-icon": "url('style/icons/blockSyncedDark.svg')",
  "tab-icon-balance": "url('style/icons/sidebarBalanceDark.svg')",
  "tab-icon-transactions": "url('style/icons/transactionsDefaultDark.svg')",
  "tab-icon-tickets": "url('style/icons/ticketsDefaultDark.svg')",
  "sidebar-balance-icon": "url('style/icons/sidebarBalanceDark.svg')",
  "testnet-logo": "url('style/icons/testnetLogoDark.svg')",
  "mainnet-logo": "url('style/icons/decredLogoDark.svg')",
  createnewwallet: "url('style/icons/createnewwalletDark.svg')",
  "wallet-blue-icon": "url('style/icons/walletBlueDark.svg')",
  "wallet-gray-icon": "url('style/icons/walletGrayDark.svg')",
  blockchain: "url('style/icons/blockchainDark.svg')",
  "blockchain-default": "url('style/icons/blockchainDefaultDark.svg')",
  "blockchain-initial": "url('style/icons/blockchainInitialDark.svg')",
  "launcher-edit-wallets": "url('style/icons/editDefaultDark.svg')",
  "launcher-edit-wallets-hover": "url('style/icons/editHoverDark.svg')",
  "onboarding-checkcircle": "url('style/icons/onboardingCheckcircleDark.svg')",
  "x-grey": "url('style/icons/xGreyDark.svg')",
  "copy-to-clipboard-icon": "url('style/icons/copyToClipboardBlueDark.svg')",
  "stakey-privacy-standard": "url('style/icons/privacyStandardDark.svg')",
  "stakey-privacy-disabled": "url('style/icons/privacyDisabledDark.svg')",
  "stakey-privacy-custom": "url('style/icons/privacyCustomDark.svg')",
  "header-transactions": "url('style/icons/transactionsHeaderDark.svg')",
  "header-governance": "url('style/icons/governanceHeaderDark.svg')",
  "header-tickets": "url('style/icons/ticketsHeaderDark.svg')",
  "header-accounts": "url('style/icons/accountsHeaderDark.svg')",
  "header-lightning": "url('style/icons/lightningHeaderDark.svg')",
  "header-security": "url('style/icons/privacyHeaderDark.svg')",
  "header-trezor": "url('style/icons/trezorHeaderDark.svg')",
  "help-docs": "url('style/icons/docsGreyDark.svg')",
  "help-github": "url('style/icons/githubGreyDark.svg')",
  "help-forum": "url('style/icons/forumGreyDark.svg')",
  "help-stakepools": "url('style/icons/stakepoolsGreyDark.svg')",
  "help-matrix": "url('style/icons/matrixGreyDark.svg')",
  "help-blockchain-explorer":
    "url('style/icons/blockchainExplorerGreyDark.svg')",
  "help-constitution": "url('style/icons/constitutionGreyDark.svg')",
  "help-star": "url('style/icons/starGreyDark.svg')",
  "help-external-default": "url('style/icons/externalDefaultDark.svg')",
  "help-external-hover": "url('style/icons/externalHoverDark.svg')",
  "help-expand-default": "url('style/icons/expandDefaultDark.svg')",
  "help-expand-hover": "url('style/icons/expandHoverDark.svg')",
  "menu-arrow-up": "url('style/icons/menuArrowUpDark.svg')",
  "agenda-close-icon": "url('style/icons/ticketsAgendaCloseDark.svg')",
  "tickets-info-icon": "url('style/icons/ticketsInfoDark.svg')",
  "agenda-card-kebab": "url('style/icons/ticketsAgendaCardKebabDark.svg')",
  "arrow-right-gray-icon": "url('style/icons/arrowRightGrayDark.svg')",
  "send-self-default": "url('style/icons/sendSelfDefaultDark.svg')",
  "send-all-default": "url('style/icons/sendMaxDefaultDark.svg')",
  "search-icon": "url('style/icons/searchDark.svg')",
  "wallet-tutorial-check-circle":
    "url('style/icons/walletTutorialCheckcircleDark.svg')",
  "importscript-icon": "url('style/icons/importScriptDark.svg')",
  "stakepool-stats-active-icon": "url('style/icons/stakepoolsActiveDark.svg')",
  "accounts-default": "url('style/icons/accountDefaultDark.svg')",
  "accounts-imported": "url('style/icons/accountImportedDark.svg')",
  password: "url('style/icons/passwordDark.svg')",
  "tx-details-arrow-left": "url('style/icons/txDetailsArrowLeftDark.svg')",
  "stake-pool-icon": "url('style/icons/stakepoolDark.svg')",
  "expiry-icon": "url('style/icons/expiryDark.svg')",
  "split-fee-icon": "url('style/icons/splitFeeDark.svg')",
  "pool-fee-icon": "url('style/icons/poolFeesDark.svg')",
  "tickets-cogs-opened-icon": "url('style/icons/ticketsCogsOpenedDark.svg')",
  "ticket-address-icon": "url('style/icons/votingAddressDark.svg')",
  "fee-address-icon": "url('style/icons/poolFeeAddressDark.svg')",
  "sort-by-icon": "url('style/icons/sortbyDark.svg')",
  "contextbutton-eye-default-icon":
    "url('style/icons/contextbuttonEyeDefaultDark.svg')",
  "launcher-logo": "url('style/icons/launcherLogoDark.svg')",
  "help-getstared": "url('style/icons/helpGetstaredDark.svg')",
  "no-tx-icon": "url('style/icons/noTxDark.svg')",
  "ticket-reward-icon": "url('style/icons/blockRewardDark.svg')",
  "time-lock-icon": "url('style/icons/timeLockDark.svg')",
  "small-logo": "url('style/icons/logoDark.svg')",
  "stakepool-stats-icon": "url('style/icons/stakepoolsDefaultDark.svg')",
  "vote-time-stats-icon": "url('style/icons/voteTimeDefaultDark.svg')",
  "vote-time-stats-active-icon": "url('style/icons/voteTimeActiveDark.svg')",
  "stakerewards-stats-icon": "url('style/icons/stakeRewardsDefaultDark.svg')",
  "stakerewards-stats-active-icon":
    "url('style/icons/stakeRewardsActiveDark.svg')",
  "send-self-hover": "url('style/icons/sendSelfHoverDark.svg')",
  "send-all-hover": "url('style/icons/sendMaxHoverDark.svg')",
  "select-arrow-up": "url('style/icons/selectArrowUpDark.svg')",
  "info-icon": "url('style/icons/informationDark.svg')",
  "menu-cancel-rescan-icon": "url('style/icons/menuCancelRescanDark.svg')",
  "politeia-loading-icon": "url('style/icons/politeia-loading-dark.gif')",
  "backup-icon": "url('style/icons/harddriveDark.svg')",
  "loader-animation-daemon-waiting-initial":
    "url('style/icons/daemonWaitingLoaderInitialDark.gif')",
  "mixed-account-icon": "url('style/icons/mixedAccountDark.svg')",
  "unmixed-account-icon": "url('style/icons/unmixedAccountDark.svg')",
  "privacy-running-arrows": "url('style/icons/mixerArrowsDark.gif')",
  "decentralized-loop-still":
    "url('style/icons/decentralizedLoopStillDark.svg')",
  "decentralized-loop-animation":
  "url('style/icons/decentralizedLoopAnimationDark.gif')",
  "self-transaction-icon": "url('style/icons/sentToSelfTxDark.svg')",
  "proposals-refresh-icon": "url('style/icons/menuMixerDark.svg')"
};

export default darkTheme;
