const lightTheme = {
  "background-back-color": "#fff",
  "background-container": "#f3f5f6",
  "background-container-opaque": "rgba(243, 245, 246, 0.895)",
  "background-container-hover": "#f0f4f4",
  "background-hovered": "#e9f8fe",
  "input-color-default": "#091440",
  "input-color-hovered": "#091440",
  "input-color-focused": "#091440",
  "input-color-disabled": "#dadfe2",
  "input-color-shadow": "rgba(9, 20, 64, 0.21)",
  "button-text": "#48566e",
  "white-button-text": "#fff",
  "title-text-and-button-background": "#48566e",
  "title-text-and-button-background-hovered": "rgba(72, 86, 110, 0.7)",
  "title-text-and-button-background-drop-shadow": "rgba(72, 86, 110, 0.34)",
  "stroke-color-default": "#a9b4bf",
  "stroke-color-hovered": "#596d81",
  "stroke-color-focused": "#2970ff",
  "input-color": "#2970ff",
  "input-color-blue-shadow": "rgba(41, 112, 255, 0.21)",
  "input-color-hover": "#1c4eb2",
  "account-button-hover": "#4a92ff",
  "link-color": "#2970ff",
  "link-hover-color": "#6397ff",
  "accent-color": "#2ed8a3",
  "blue-highlight-background": "#d3f0fd",
  "tab-text": "#9ca8b5",
  "tab-text-active-hover": "#3d5873",
  "cyan-bold": "#69d5f7",
  "disabled-color": "#8997a5",
  "disabled-background-color": "#e7eaed",
  "disabled-background-color-lighter": "#edeff1",
  "success-text-color": "#41be53",
  "error-text-color": "#fd714b",
  "error-red": "#ED6D47",
  "error-red-hover": "red",
  "vote-yes-color": "#41be53",
  "vote-no-color": "#ed6d47",
  "vote-abstain-color": "#596d81",
  "white-border": "#d1d5db",
  "display-wallet-gradient-right": "#959dac",
  "display-wallet-gradient-selected-right": "#6ed3f3",
  "tx-history-background-hover": "rgba(212, 240, 253, 0.5)",
  "sidebar-color": "#f9fafa",
  "short-separator-border": "#091440",
  "sidebar-bottom-light-text-color": "#424F67",
  "header-desc-color": "#091440",
  "sidebar-menu-link": "#8997a5",
  "linear-progress-text": "#fff",
  "wallet-label": "#091440",
  "new_wallet-label": "#48566e",
  "selected_wallet-label": "#091440",
  "wallet-desc": "#091440",
  "getstarted-menu-color": "#8997a5",
  "tutorial-header": "#091440",
  "step-indicator": "#d1d5db",
  "combobox-outer-bottom-border": "#2970ff",
  "combobox-restore-border": "#d1d5db",
  "text-toggle-button-active-bg": "#fff",
  "text-toggle-button-active-text": "#0C1E3E",
  "text-toggle-button-border": "#e7eaed",
  "text-toggle-button-bg": "#F7F8F9",
  "text-toggle-button-inactive-text": "#959DAC",
  "header-desc-lighter-color": "#091440",
  "info-modal-button-bg": "#48566e",
  "info-modal-button-text": "#fff",
  "agenda-card-bottom-cfg": "#596d81",
  "tabbed-page-header-bg": "#edeff1",
  "tabbed-page-header-active-bg": "#fff",
  "tabbed-page-header-text": "#9ca8b5",
  "overview-balance-label": "#596d81",
  "chart-axis-stroke": "#666",
  "chart-axis-text": "#a4afba",
  "disabled-background-color-dark": "#e7eaed",
  "wallet-tutorial-text": "#48566e",
  "wallet-tutorial-link": "#2970ff",
  "wallet-tutorial-step-indicator": "#d1d5db",
  "modal-text": "#48566e",
  "modal-bottom": "#48566e",
  "modal-stroke-color": "#a9b4bf",
  "settings-desc": "#8997a5",
  "wallet-close-button-bg": "#8997a5",
  "wallet-close-button-text": "#f3f6f6",
  "select-stroke-color": "#a9b4bf",
  "select-placeholder": "#091440",
  "account-text": "#8997A5",
  "account-pubkey-text": "#8997a5",
  "back-button-bg": "#48566e",
  "back-button-text": "#f3f5f6",
  "back-button-dark-text": "#f3f5f6",
  "tx-detail-text": "#596d81",
  "tx-detail-raw-shadow":
    "linear-gradient(to top, rgb(243, 246, 246, 0.6) 10%, rgb(243, 246, 246, 0.5) 20%, rgb(243, 246, 246, 0) 70%)",
  "home-content-link": "#8997a5",
  "transfer-details-bg": "#edeff1",
  "filter-menu-arrow": "#fff",
  "filter-menu-bg-hover": "#596d81",
  "menutab-hover": "#596d81",
  "tooltip-container": "#f3f5f6",
  "loader-bg": "#d1d5db",
  "display-wallet-bg":
    "linear-gradient(225deg, var(--white-border), var(--display-wallet-gradient-right))",
  "select-border": "#e7eaed",
  "toggle-switch-bg": "#d1d5db",
  "toggle-switch-knob-bg": "#8997a5",
  "transaction-account-name-bg": "#E9F8FE",
  "account-row-hover": "#f0f4f4",
  "chart-cursor-color": "#e9f8fe",
  "linear-progress-text-default": "#fff",
  "linear-progress-text-initial": "#fff",
  "onboard-toolbar-shadow": "rgba(9,20,64,0.13)",
  "onboard-toolbar-background": "#fff",
  "background-copy-color": "#e9f8ff",
  "seedword-number-color": "#C4CBD2",
  "seedword-select-border-default-border-color": "#D1D5DB",
  "seedword-select-border-default-text-color": "#C4CBD2",
  "seedword-select-border-default-hover-border-color": "#959DAC",
  "seedword-select-border-default-hover-text-color": "#48566E",
  "txdetails-top-bg": "#f9fafa",
  "input-placeholder-color": "#C4CBD2",
  "trezor-line-color": "#dadfe2",
  "proposal-text-markdown": "#f6f8fa",
  "background-address-copy-color": "#e9f8ff",
  "icons-shadow": "#09144036",
  "no-more-tickets-indicator-bg": "#E6EAED",
  "ease-in-out-quart": "cubic-bezier(0.77, 0, 0.175, 1)",
  "input-copy-hover-color": "#78d9f8",
  "coinjoin-sum-color": "#d4f0fd",
  "coinjoin-sum-text-color": "#596d81",
  "privacy-balance-color": "#091440",
  "privacy-balance-label-color": "#1B2B54",
  "privacy-balance-mixed-label-color": "#596D81",
  "privacy-mixer-status-color": "#0C1E3E",
  "mixer-settings-label": "#0C1E3E",
  "mixer-settings-disabled": "#8997A5",

  // override pi-ui's tab colors
  "tab-default-color": "transparent", // default border
  "tab-active-background": "var(--background-back-color)",
  "tab-text-active-color": "var(--input-color-default)",
  "tab-text-color": "var(--sidebar-menu-link)",

  /* icons */
  "menu-settings": "url('style/icons/menuSettings.svg')",
  "menu-accounts": "url('style/icons/accounts-active.png')",
  "menu-governance": "url('style/icons/governance-active.png')",
  "menu-transactions": "url('style/icons/transactions-active.png')",
  "menu-overview": "url('style/icons/overview-active.png')",
  "menu-privacy": "url('style/icons/privacy.svg')",
  "menu-tickets": "url('style/icons/tickets-active.png')",
  "menu-ln": "url('style/icons/lightning.svg')",
  "menu-trezor": "url('style/icons/trezorActive.svg')",
  "menu-hamburger": "url('style/icons/hamburger.svg')",
  "menu-arrow": "url('style/icons/arrow.svg')",
  "menu-mixer-icon": "url('style/icons/menuMixer.svg')",
  "menu-spvon-icon": "url('style/icons/menuSpvOn.svg')",
  "menu-spvoff-icon": "url('style/icons/menuSpvOff.svg')",
  "menu-block-synced-icon": "url('style/icons/blockSynced.svg')",
  "tab-icon-balance": "url('style/icons/balanceSelector.svg')",
  "tab-icon-transactions": "url('style/icons/transactions-default.png')",
  "tab-icon-tickets": "url('style/icons/tickets-default.png')",
  "sidebar-balance-icon": "url('style/icons/sidebar-balance.svg')",
  "testnet-logo": "url('style/icons/testnet-logo.svg')",
  "mainnet-logo": "url('style/icons/decred-logo.svg')",
  createnewwallet: "url('style/icons/createnewwallet.svg')",
  "wallet-blue-icon": "url('style/icons/wallet-blue.svg')",
  "wallet-gray-icon": "url('style/icons/wallet-gray.svg')",
  blockchain: "url('style/icons/blockchain.svg')",
  "blockchain-default": "url('style/icons/blockchainDefault.svg')",
  "blockchain-initial": "url('style/icons/blockchainInitial.svg')",
  "launcher-edit-wallets": "url('style/icons/editDefault.svg')",
  "launcher-edit-wallets-hover": "url('style/icons/editHover.svg')",
  "onboarding-checkcircle": "url('style/icons/onboarding-checkcircle.svg')",
  "x-grey": "url('style/icons/x-grey.svg')",
  "copy-to-clipboard-icon": "url('style/icons/copy-to-clipboard-blue.svg')",
  "stakey-privacy-standard": "url('style/icons/privacyStandard.svg')",
  "stakey-privacy-disabled": "url('style/icons/privacyDisabled.svg')",
  "stakey-privacy-custom": "url('style/icons/privacyCustom.svg')",
  "header-transactions": "url('style/icons/transactionsHeader.svg')",
  "header-governance": "url('style/icons/governanceHeader.svg')",
  "header-tickets": "url('style/icons/ticketsHeader.svg')",
  "header-accounts": "url('style/icons/accountsHeader.svg')",
  "header-lightning": "url('style/icons/lightningHeader.svg')",
  "header-security": "url('style/icons/privacyHeader.svg')",
  "header-trezor": "url('style/icons/trezorHeader.svg')",
  "help-docs": "url('style/icons/docsGrey.svg')",
  "help-github": "url('style/icons/githubGrey.svg')",
  "help-forum": "url('style/icons/forumGrey.svg')",
  "help-stakepools": "url('style/icons/stakepoolsGrey.svg')",
  "help-matrix": "url('style/icons/matrixGrey.svg')",
  "help-blockchain-explorer": "url('style/icons/blockchainExplorerGrey.svg')",
  "help-constitution": "url('style/icons/constitutionGrey.svg')",
  "help-star": "url('style/icons/starGrey.svg')",
  "help-external-default": "url('style/icons/externalDefault.svg')",
  "help-external-hover": "url('style/icons/externalHover.svg')",
  "help-expand-default": "url('style/icons/expandDefault.svg')",
  "help-expand-hover": "url('style/icons/expandHover.svg')",
  "menu-arrow-up": "url('style/icons/menu-arrow-up.svg')",
  "agenda-close-icon": "url('style/icons/tickets-agenda-close.svg')",
  "tickets-info-icon": "url('style/icons/tickets-info.svg')",
  "agenda-card-kebab": "url('style/icons/tickets-agenda-card-kebab.svg')",
  "arrow-right-gray-icon": "url('style/icons/arrow-right-gray.svg')",
  "send-self-default": "url('style/icons/sendSelfDefault.svg')",
  "send-all-default": "url('style/icons/sendMaxDefault.svg')",
  "search-icon": "url('style/icons/search.svg')",
  "wallet-tutorial-check-circle":
    "url('style/icons/walletTutorialCheckcircle.svg')",
  "importscript-icon": "url('style/icons/import-script.svg')",
  "stakepool-stats-active-icon": "url('style/icons/stakepoolsActive.svg')",
  "accounts-default": "url('style/icons/accountDefault.svg')",
  "accounts-imported": "url('style/icons/accountImported.svg')",
  password: "url('style/icons/password.svg')",
  "tx-details-arrow-left": "url('style/icons/txDetailsArrowLeft.svg')",
  "stake-pool-icon": "url('style/icons/stake-pool.svg')",
  "expiry-icon": "url('style/icons/expiry.svg')",
  "split-fee-icon": "url('style/icons/split-fee.svg')",
  "pool-fee-icon": "url('style/icons/pool-fees.svg')",
  "tickets-cogs-opened-icon": "url('style/icons/tickets-cogs-opened.svg')",
  "ticket-address-icon": "url('style/icons/voting-address.svg')",
  "fee-address-icon": "url('style/icons/pool-fee-address.svg')",
  "sort-by-icon": "url('style/icons/sort-by.svg')",
  "contextbutton-eye-default-icon":
    "url('style/icons/contextbutton-eye-default.svg')",
  "launcher-logo": "url('style/icons/launcher-logo.svg')",
  "help-getstared": "url('style/icons/help-active.png')",
  "no-tx-icon": "url('style/icons/no-tx.svg')",
  "ticket-reward-icon": "url('style/icons/blockReward.svg')",
  "time-lock-icon": "url('style/icons/time-lock.svg')",
  "small-logo": "url('style/icons/logo.svg')",
  "stakepool-stats-icon": "url('style/icons/stakepoolsDefault.svg')",
  "vote-time-stats-icon": "url('style/icons/voteTimeDefault.svg')",
  "vote-time-stats-active-icon": "url('style/icons/voteTimeActive.svg')",
  "stakerewards-stats-icon": "url('style/icons/stakeRewardsDefault.svg')",
  "stakerewards-stats-active-icon": "url('style/icons/stakeRewardsActive.svg')",
  "send-self-hover": "url('style/icons/sendSelfHover.svg')",
  "send-all-hover": "url('style/icons/sendMaxHover.svg')",
  "select-arrow-up": "url('style/icons/select-arrow-up.svg')",
  "info-icon": "url('style/icons/information.svg')",
  "menu-cancel-rescan-icon": "url('style/icons/menu-cancel-rescan.svg')",
  "politeia-loading-icon": "url('style/icons/politeia-loading.gif')",
  "backup-icon": "url('style/icons/harddrive.svg')",
  "loader-animation-daemon-waiting-initial":
    "url('style/icons/daemon_waiting_loader.gif')",
  "mixed-account-icon": "url('style/icons/mixedAccount.svg')",
  "unmixed-account-icon": "url('style/icons/unmixedAccount.svg')",
  "privacy-running-arrows": "url('style/icons/mixerArrows.gif')",
  "decentralized-loop-still": "url('style/icons/decentralizedLoopStill.svg')",
  "decentralized-loop-animation":
    "url('style/icons/decentralizedLoopAnimation.gif')",
  "self-transaction-icon": "url('style/icons/sentToSelfTx.svg')",
  "proposals-refresh-icon": "url('style/icons/MixerDark.svg')"
};

export default lightTheme;
