// @flow
import React from "react";
import KeyBlueButton from "../KeyBlueButton";
import "../../style/ReactSelectGlobal.less";
import "../../style/CreateWalletForm.less";

const CreateWallet = ({
  mnemonic,
  createWalletConfirmNewSeed
}) => (
  <div className="new-seed">
    <div className="help-text">
      <div className="paragraph left">Wallets are determinstically generated by a wallet seed. The seed is a master key of your wallet and the entire wallet can be recreated at any time using it. If the wallet encryption passphrase is forgotten or the wallet is destroyed, the seed can be used to recover the wallet. <span className="cyan-bold">Write down the following seed and save it in a secure location.</span>
        <br/>
        <br/><span className="cyan-regular">The next prompt will require entering this seed to confirm it has been saved.</span>
      </div>
      <div className="paragraph right">To help avoid permanent loss of your wallet,
        <br/>the seed must be backed up before continuing.
        <br/>
        <br/>
        <span className="orange-warning">Warning:</span> Failure to keep this seed private can result in the theft of your entire wallet. Under no circumstances should this seed ever be revealed to someone else.
      </div>
    </div>
    <div className="seed">{mnemonic}</div>
    <KeyBlueButton className="wallet-key-blue-button" onClick={createWalletConfirmNewSeed}>Continue</KeyBlueButton>
  </div>
);

export default CreateWallet;
