// @flow
import React from "react";
import KeyBlueButton from "../KeyBlueButton";
import "../react-select.global.css";
import styles from "./styles";

const CreateWallet = ({
  mnemonic,
  createWalletConfirmNewSeed
}) => (
  <div style={styles.contentNewSeed}>
    <div style={styles.contentParagraphRight}>Wallets are determinstically generated by a wallet seed. The seed is a master key of your wallet and the entire wallet can be recreated at any time using it. If the wallet encryption passphrase is forgotten or the wallet is destroyed, the seed can be used to recover the wallet. <span style={styles.paragraphCyanBold}>Write down the following seed and save it in a secure location.</span>
      <br/>
      <br/><span style={styles.paragraphCyanRegular}>The next prompt will require entering this seed to confirm it has been saved.</span>
    </div>
    <div style={styles.contentParagraphLeft}>To help avoid permanent loss of your wallet,
      <br/>the seed must be backed up before continuing.
      <br/>
      <br/>
      <span style={styles.paragraphOrangeWarning}>Warning:</span> Failure to keep this seed private can result in the theft of your entire wallet. Under no circumstances should this seed ever be revealed to someone else.
    </div>
    <div style={{clear: "both"}}></div>
    <div style={styles.contentSeed}>{mnemonic}</div>
    <KeyBlueButton
      style={styles.viewButtonKeyBlueWalletNewSeed}
      onClick={createWalletConfirmNewSeed}
    >Continue</KeyBlueButton>
  </div>
);

export default CreateWallet;
