const styles = {
  contentNewSeed: {
    paddingRight: "80px",
    paddingLeft: "80px",
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  contentParagraphRight: {
    float: "left",
    width: "300px",
    marginBottom: "30px",
    color: "#B7D1F0",
    fontSize: "13px",
    lineHeight: "16px",
  },
  contentParagraphLeft: {
    float: "right",
    width: "300px",
    marginBottom: "30px",
    color: "#B7D1F0",
    fontSize: "13px",
    lineHeight: "16px",
  },
  paragraphCyanBold: {
    color: "#69D5F7",
    fontWeight: "700",
  },
  paragraphCyanRegular: {
    color: "#69D5F7",
  },
  paragraphOrangeWarning: {
    color: "#FD714B",
  },
  contentSeed: {
    height: "auto",
    minHeight: "140px",
    marginBottom: "20px",
    padding: "14px 20px",
    border: "1px solid #69D5F7",
    borderRadius: "5px",
    backgroundColor: "#E9F8FE",
    fontFamily: "Inconsolata,monospace",
    color: "#000",
    fontSize: "16px",
    lineHeight: "29px",
  },
  viewButtonKeyBlueWalletNewSeed: {
    float: "left",
  },
  contentNewSeedConfirmSeed: {
    height: "200px",
  },
  contentNewSeedPrivPass: {
    paddingTop: "10px",
    height: "80px",
  },
  contentNewSeedCreateButton: {
    height: "60px",
  },
  contentConfirmWalletCreateInputLeft: {
    width: "160px",
    marginRight: "20px",
    float: "left",
    color: "#E7EAED",
    fontSize: "19px",
    textAlign: "right",
    letterSpacing: "-0.1px",
  },
  contentConfirmWalletCreateInputLeftPadding: {
    width: "160px",
    marginRight: "20px",
    float: "left",
    color: "#E7EAED",
    fontSize: "19px",
    textAlign: "right",
    letterSpacing: "-0.1px",
    paddingTop: "23px",
  },
  contentConfirmWalletCreateInputRight: {
    width: "540px",
    float: "left",
    clear: "right",
  },
  contentConfirmWalletCreateInputRightPadding: {
    marginBottom: "5px",
    width: "300px",
    paddingTop: "11px",
    float: "left",
    clear: "right",
  },
  inputPrivatePassword: {
    backgroundColor: "transparent",
    width: "100%",
    minHeight: "44px",
    paddingRight: "10px",
    paddingLeft: "10px",
    borderStyle: "none none solid",
    borderBottom: "1px solid #69D5F7",
    color: "#69D5F7",
    fontSize: "19px",
    lineHeight: "normal",
    margin: "0px",
    boxSizing: "border-box",
  },
  inputSeedTextArea: {
    backgroundColor: "transparent",
    width: "100%",
    minHeight: "108px",
    paddingRight: "10px",
    paddingLeft: "10px",
    borderStyle: "none none solid",
    borderWidth: "0px 0px 1px",
    borderColor: "#000 #000 #69D5F7",
    fontFamily: "Inconsolata,monospace",
    color: "#2971FF",
    fontSize: "13px",
    overflow: "auto",
    margin: "0px",
  },
  inputForm: {
    MozAppearance: "none !important",
    position: "relative",
    width: "100%",
    height: "auto",
    minHeight: "44px",
  },
  inputFormConfirmSeed: {
    MozAppearance: "none !important",
    position: "relative",
    width: "100%",
    height: "200px",
    minHeight: "44px",
  },
  inputFormError: {
    color: "red",
  }
};

export default styles;
