// @flow
import Add from "../icons/add.svg";
import Delete from "../icons/delete.svg";
import IndicatorPending from "../icons/indicator-pending.svg";
import IndicatorConfirmed from "../icons/indicator-confirmed.svg";
import PlusBig from "../icons/plus-big.svg";
import MinusBig from "../icons/minus-big.svg";
import ArrowDownMidBlue from "../icons/arrow-down-mid-blue.svg";
import ArrowDownKeyBlue from "../icons/arrow-down-key-blue.svg";
import ArrowUpLightBlue from "../icons/arrow-up-light-blue.svg";
import ArrowUpTurquiose from "../icons/arrow-up-turquiose.svg";
import ArrowRightKeyBlue from "../icons/arrow-right-key-blue.svg";
import Search from "../icons/search.svg";
import WalletGray from "../icons/wallet-gray.svg";
import StakePoolIcon from "../icons/stake-pool.svg";
import ExpiryIcon from "../icons/expiry.svg";
import SplitFeeIcon from "../icons/split-fee.svg";
import TicketAddressIcon from "../icons/voting-address.svg";
import FeeAddressIcon from "../icons/pool-fee-address.svg";
import PoolFeeIcon from "../icons/pool-fees.svg";
import BalanceToMaintainIcon from "../icons/balance-to-maintain.svg";
import MaxFeeIcon from "../icons/max-fee.svg";
import MaxPriceAbsoluteIcon from "../icons/max-price-absolute.svg";
import MaxPriceRelativeIcon from "../icons/max-price-relative.svg";
import MaxPerBlockIcon from "../icons/max-per-block.svg";
import TicketSmall from "../icons/tickets-ticket.svg";

export const ReceiveStyles = {
  body: {
    position: "fixed",
    left: "0px",
    top: "50%",
    right: "0px",
    display: "block",
    overflow: "hidden",
    width: "1178px",
    height: "770px",
    marginTop: "-385px",
    marginRight: "auto",
    marginLeft: "auto",
    backgroundColor: "#FFF",
  },
  view: {
    width: "880px",
    height: "100%",
    float: "right",
    backgroundColor: "#f3f6f6",
  },
  content: {
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  center: {
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  selectAccounts: {
    display: "block",
    overflow: "hidden",
    width: "100%",
    height: "100%",
    color: "#0c1e3e",
    fontSize: "19px",
    ":hover": {
      height: "auto",
    }
  },
  selectAccountsN: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    paddingTop: "18px",
    paddingBottom: "18px",
    paddingLeft: "10px",
    float: "left",
    ":hover": {
      color: "#2971ff",
    }
  },
  fromAccount: {
    fontSize: "13px",
  },
  fromAccountBold: {
    fontWeight: "bold"
  },
  selectAccountsArea: {
    width: "50%",
    marginLeft: "190px",
    paddingBottom: "16px",
    paddingTop: "6px",
  },
  headerTitleReceive: {
    height: "54px",
    lineHeight: "49px",
    color: "#596d81",
    fontSize: "27px",
    textTransform: "capitalize",
    paddingLeft: "50px",
    backgroundImage: `url(${PlusBig})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "30px",
    backgroundRepeat: "no-repeat",
  },
  headerMetaReceive: {
    height: "54px",
    width: "480px",
    paddingLeft: "50px",
    color: "#0c1e3e",
    fontSize: "14px",
  },
  contentNestReceive: {
    backgroundColor: "#fff",
    paddingTop: "1px",
    height: "235px",
  },
  contentNestReceiveForAddress: {
    width: "100%",
    height: "54px",
    paddingTop: "10px",
    paddingLeft: "20px",
  },
  contentNestReceiveForAddressIcon: {
    display: "inline-block",
    width: "34px",
    height: "34px",
    float: "right",
    paddingRight: "140px",
    backgroundImage: `url(${WalletGray})`,
    backgroundPosition: "0% 50%",
    backgroundSize: "20px auto",
    backgroundRepeat: "no-repeat",
  },
  contentNestPrefixReceive: {
    paddingRight: "0px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "19px",
    textAlign: "right",
    textTransform: "capitalize",
  },
  contentNestCopyToClipboardIcon: {
    marginLeft: "16px",
  },
  contentNestQR: {
    width: "100%",
    minHeight: "140px",
    padding: "20px",
    float: "left",
    textAlign: "center",
  },
  contentNestQRHash: {
    width: "544px",
    height: "138px",
    lineHeight: "138px",
    float: "left",
    border: "1px solid #69d5f7",
    borderRadius: "5px",
    backgroundColor: "#e9f8fe",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "25px",
    fontWeight: "700",
  },
  contentNestQRImage: {
    width: "140px",
    height: "140px",
    float: "right",
    paddingRight: "36px",
    backgroundPosition: "50% 50%",
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
  },
  contentReceive: {
    marginTop: "20px",
    textAlign: "center",
  },
  receiveSelectAccountInput: {
    width: "380px",
    float: "left",
    paddingLeft: "20px",
  }
};
export const SendStyles = {
  body: {
    position: "fixed",
    left: "0px",
    top: "50%",
    right: "0px",
    display: "block",
    overflow: "hidden",
    width: "1178px",
    height: "770px",
    marginTop: "-385px",
    marginRight: "auto",
    marginLeft: "auto",
    backgroundColor: "#FFF",
  },
  view: {
    width: "880px",
    height: "100%",
    float: "right",
    backgroundColor: "#f3f6f6",
  },
  viewNotificationError: {
    marginTop: "20px",
    display: "inline-block",
    marginRight: "auto",
    marginLeft: "auto",
    padding: "7px 20px 7px 7px",
    borderRadius: "5px",
    backgroundColor: "#fd714b",
    boxShadow: "0 3px 10px 0 rgba(0, 0, 0, .2)",
    color: "#fff",
    fontSize: "13px",
    textAlign: "center",
  },
  viewNotificationSuccess: {
    marginTop: "20px",
    display: "inline-block",
    marginRight: "auto",
    marginLeft: "auto",
    padding: "7px 20px 7px 7px",
    borderRadius: "5px",
    backgroundColor: "#41bf53",
    boxShadow: "0 3px 10px 0 rgba(0, 0, 0, .2)",
    color: "#fff",
    fontSize: "13px",
    textAlign: "center",
    textDecoration: "none",
  },
  sendAddressDeleteIconHeader: {
    width: "26px",
    height: "19px",
    float: "left",
    backgroundImage: `url(${Delete})`,
    backgroundPosition: "50% 50%",
    backgroundSize: "8px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      opacity: "0.85",
    }
  },
  transition1: {
    transition: "all 100ms ease-in-out",
  },
  headerTitleSend: {
    height: "54px",
    lineHeight: "49px",
    color: "#596d81",
    fontSize: "27px",
    textTransform: "capitalize",
    paddingLeft: "50px",
    backgroundImage: `url(${MinusBig})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "30px",
    backgroundRepeat: "no-repeat",
  },
  headerMetaSend: {
    height: "54px",
    width: "480px",
    paddingLeft: "50px",
    color: "#0c1e3e",
    fontSize: "14px",
  },
  content: {
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  contentBlur: {
    filter: "blur(6px)",
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  sendSend: {
    paddingTop: "1px",
    backgroundColor: "#fff",
  },
  sendDeleteAddress: {
    width: "625px",
    height: "54px",
    paddingTop: "10px",
    paddingLeft: "116px",
    float: "left",
  },
  sendSelectAccountArea: {
    width: "100%",
    height: "62px",
    marginTop: "10px",
  },
  sendSelectAccountInput: {
    width: "290px",
    float: "left",
  },
  sendRow: {
    width: "100%",
    height: "47px",
    float: "left",
  },
  sendOutputRow: {
    width: "100%",
    height: "27px",
    float: "left",
  },
  sendOutputErrorRow: {
    width: "100%",
    height: "12px",
    float: "left",
    fontSize: "11px",
  },
  sendOutputAddressError: {
    color: "red",
    float: "left",
    width: "290px",
    paddingLeft: "110px",
  },
  sendOutputAmountError: {
    color: "red",
    float: "right",
    width: "180px",
    textAlign: "right",
    paddingRight: "59px",
  },
  sendOutputPrivPassError: {
    color: "red",
    float: "left",
    width: "223px",
    paddingRight: "11px",
  },
  sendLabel: {
    width: "65px",
    float: "left",
    paddingRight: "15px",
    paddingTop: "5px",
    fontSize: "20px",
    textAlign: "right",
  },
  sendAddress: {
    width : "300px",
    float: "left",
  },
  sendAmount: {
    width : "300px",
    float: "left",
  },
  sendPrefixSend: {
    width: "100px",
    paddingRight: "15px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "19px",
    textAlign: "right",
    textTransform: "capitalize",
  },
  sendPrefixConfirm: {
    width: "230px",
    paddingRight: "15px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "19px",
    textAlign: "right",
    textTransform: "capitalize",
  },
  sendFromAddress: {
    width: "100%",
    height: "54px",
    paddingTop: "10px",
    float: "left",
  },
  sendFromAddressWalletIcon: {
    display: "inline-block",
    width: "60px",
    height: "34px",
    float: "left",
    backgroundImage: `url(${WalletGray})`,
    backgroundPosition: "50% 50%",
    backgroundSize: "20px",
    backgroundRepeat: "no-repeat",
  },
  sendToAddress: {
    width: "100%",
    height: "54px",
    paddingTop: "10px",
    float: "left",
  },
  sendAddressHashTo: {
    width: "96%",
    height: "100%",
    padding: "9px 0px 4px 10px",
    borderStyle: "none",
    borderBottom: "1px solid",
    color: "#2971ff",
    fontSize: "13px",
    cursor: "text",
    ":focus": {
      color: "#2971ff",
    },
  },
  sendAddressHashBlock: {
    width: "299px",
    height: "34px",
    float: "left",
    paddingLeft: "81px",
    fontSize: "13px",
  },
  sendAddressSignPrivPass: {
    width: "299px",
    height: "34px",
    float: "left",
    fontSize: "13px",
  },
  sendAddressHashBlockConfirm: {
    position: "relative",
    overflow: "hidden",
    width: "300px",
    height: "34px",
    paddingTop: "7px",
    float: "left",
    fontSize: "17px",
  },
  sendAmountLabel: {
    float: "left",
    width: "26%",
    paddingLeft: "10px",
    paddingTop: "5px",
    fontSize: "20px",
  },
  selectAccountsSend: {
    width: "300px",
    position: "relative",
    zIndex: "3",
    overflow: "visible",
    height: "34px",
    minWidth: "300px",
    float: "left",
    borderBottom: "1px solid #2971ff",
    backgroundColor: "#fff",
    backgroundImage: `url(${ArrowDownMidBlue})`,
    backgroundPosition: "100% 50%",
    backgroundSize: "10px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      backgroundImage: `url(${ArrowDownKeyBlue})`,
      backgroundSize: "10px",
    }
  },
  selectAccount: {
    display: "block",
    overflow: "hidden",
    width: "100%",
    height: "100%",
    color: "#0c1e3e",
    fontSize: "19px",
    ":hover": {
      height: "auto",
    }
  },
  selectAccountNFirst: {
    overflow: "hidden",
    height: "34px",
    marginRight: "20px",
    paddingTop: "5px",
    paddingLeft: "10px",
    color: "#2971ff",
    fontSize: "19px",
  },
  selectAccountNTextSend: {
    width: "200%",
    paddingTop: "1px",
    fontSize: "13px",
  },
  selectAccountNAmount: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    marginRight: "20px",
    paddingTop: "7px",
    paddingLeft: "40px",
    backgroundImage: "linear-gradient(90deg, transparent, #fff 28%)",
    fontFamily: "Inconsolata, monospace",
    color: "#596d81",
    fontSize: "11px",
    fontWeight: "400",
    textAlign: "right",
  },
  selectAccountNAmountBold: {
    fontFamily: "Inconsolata, monospace",
    fontWeight: "700",
  },
  selectAccountNNestSend: {
    fontSize: "13px",
    overflow: "auto",
    height: "auto",
    maxHeight: "413px",
    paddingTop: "10px",
    paddingBottom: "10px",
    borderBottom: "1px solid #a9b4bf",
    backgroundColor: "#fff",
  },
  selectAccountNGradient: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    width: "40px",
    height: "100%",
    backgroundImage: "linear-gradient(90deg, transparent, #fff 75%)",
  },
  selectAccountN: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    paddingTop: "18px",
    paddingBottom: "18px",
    paddingLeft: "10px",
    float: "left",
    ":hover": {
      color: "#2971ff",
    }
  },
  selectAccountNText: {
    width: "200%",
  },
  inputForm: {
    position: "relative",
    width: "100%",
    height: "auto",
    minHeight: "44px",
  },
  sendAddressWalletIcon: {
    width: "39px",
    height: "34px",
    float: "left",
    backgroundImage: `url(${Add})`,
    backgroundPosition: "50% 50%",
    backgroundSize: "19px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      opacity: "0.85",
    }
  },
  sendAddressAmount: {
    display: "block",
    height: "34px",
    float: "right",
  },
  sendAddressInputAmount: {
    width: "68%",
    float: "left",
    height: "100%",
    padding: "9px 10px 4px 10px",
    borderStyle: "none",
    borderBottom: "1px solid",
    color: "rgb(41, 113, 255)",
    fontSize: "13px",
    textAlign: "right",
    cursor: "text",
  },
  sendAddressAmountSumAndCurrency: {
    position: "relative",
    overflow: "hidden",
    width: "70%",
    height: "100%",
    float: "right",
    color: "#0c1e3e",
    textAlign: "right",
  },
  sendAddressAmountSumGradient: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    display: "inline-block",
    width: "37px",
    height: "100%",
    paddingTop: "7px",
    paddingRight: "10px",
    backgroundColor: "#fff",
    fontFamily: "Inconsolata, monospace",
    fontSize: "13px",
    textTransform: "uppercase",
  },
  sendAddressAmountSum: {
    display: "block",
    width: "100px",
    height: "100%",
    borderStyle: "none",
    fontFamily: "Inconsolata, monospace",
    fontSize: "19px",
    fontWeight: "700",
  },
  sendToAddressAmountSumNumberFormatSmall: {
    fontSize: "13px",
  },
  sendAddressDeleteIcon: {
    width: "39px",
    height: "34px",
    float: "left",
    backgroundImage: `url(${Delete})`,
    backgroundPosition: "50% 50%",
    backgroundSize: "8px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      opacity: "0.85",
    }
  },
  sendAddressAmountSumNumberFormatSmall: {
    fontSize: "13px",
  },
  contentSend: {
    float: "left",
    marginTop: "20px",
  },
  contentSendSection: {
    display: "block",
    width: "91%",
    height: "22px",
    paddingLeft: "30px",
    float: "left",
    color: "#0c1e3e",
  },
  contentSendSectionCheckboxText: {
    height: "100%",
    paddingTop: "1px",
    paddingLeft: "5px",
    float: "left",
    textTransform: "capitalize",
  },
  contentSendSectionAmount: {
    width: "160px",
    height: "100%",
    paddingTop: "1px",
    paddingRight: "30px",
    float: "right",
    fontFamily: "Inconsolata, monospace",
    fontSize: "13px",
    textAlign: "right",
  },
  contentSendSectionDescription: {
    height: "100%",
    paddingTop: "1px",
    paddingRight: "20px",
    float: "right",
    color: "#596d81",
    fontSize: "13px",
  },
  contentSendSectionAmountCurrency: {
    paddingLeft: "5px",
  },
  flexHeight: {
    paddingTop: "1px",
    backgroundColor: "#fff",
    overflowY: "auto",
    overflowX: "hidden",
  },
  loading: {
    marginTop: "110px",
    marginLeft: "268px",
  },
  totalAmountSend: {
    float: "right",
    width: "275px",
    paddingRight: "10px",
    fontSize: "15px",
    textAlign: "right",
  },
  totalAmountSendText: {
    float: "left",
    paddingBottom: "5px",
  },
  estimationAreaSend: {
    paddingTop:"10px",
    float: "right",
    height: "100%",
    width:"300px",
  },
  totalAmountSendAmount: {
    float: "right",
    fontFamily: "Inconsolata, monospace",
  },
  sendButtonArea: {
    width: "100%",
    height: "100px",
  }
};
export const HomeStyles = {
  body: {
    position: "fixed",
    left: "0px",
    top: "50%",
    right: "0px",
    display: "block",
    overflow: "hidden",
    width: "1178px",
    height: "770px",
    marginTop: "-385px",
    marginRight: "auto",
    marginLeft: "auto",
    backgroundColor: "#FFF",
  },
  view: {
    width: "880px",
    height: "100%",
    float: "right",
    backgroundColor: "#f3f6f6",
  },
  content: {
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  rescanProgressArea: {
    fontSize: "16px",
  },
  rescanProgressPercent: {
    float: "right",
  },
  rescanProgressFraction: {
    float: "left",
  },
  rescanButtonArea: {
    float: "right",
  },
  rescanButtonMessage: {
    color: "#596d81",
    fontSize: "13px",
    float: "left",
    width: "100%",
  },
  contentTitle: {
    display: "block",
    height: "44px",
    marginRight: "auto",
    marginBottom: "10px",
    marginLeft: "auto",
    borderBottom: "1px solid transparent",
    color: "#596d81",
    fontSize: "27px",
  },
  contentNest: {
    paddingTop: "1px",
  },
  contentTitleText: {
    display: "inline-block",
    overflow: "hidden",
    width: "600px",
    height: "100%",
    paddingTop: "13px",
    paddingRight: "20px",
    paddingLeft: "20px",
    float: "left",
  },

  contentTitleButtonSearch: {
    width: "60px",
    height: "100%",
    cursor: "pointer",
    paddingRight: "20px",
    paddingLeft: "20px",
    float: "right",
    backgroundImage: `url(${Search})`,
    backgroundPosition: "50% 50%",
    backgroundSize: "20px",
    backgroundRepeat: "no-repeat",
    ":hover": {
      opacity: "0.8",
    }
  },

  contentTitleButtonSearchTransition1: {
    width: "60px",
    height: "100%",
    cursor: "pointer",
  },

  contentTitleTextActive: {
    color: "#2971ff",
  },

  contentTitleActive: {
    borderBottom: "1px solid #2971ff",
  },

  headerMetaCurrency: {
    fontSize: "23px",
  },
  viewNotificationNotSynced: {
    display: "inline-block",
    marginRight: "auto",
    marginLeft: "auto",
    padding: "7px 20px",
    borderRadius: "5px",
    backgroundColor: "#666666",
    boxShadow: "0 3px 10px 0 rgba(0, 0, 0, .2)",
    color: "#fff",
    fontSize: "13px",
    textAlign: "center",
  },
  loading: {
    marginTop: "110px",
    marginLeft: "268px",
  },
};
export const SettingStyles = {
  body: {
    position: "fixed",
    left: "0px",
    top: "50%",
    right: "0px",
    display: "block",
    overflow: "hidden",
    width: "1178px",
    height: "770px",
    marginTop: "-385px",
    marginRight: "auto",
    marginLeft: "auto",
    backgroundColor: "#FFF",
  },
  view: {
    width: "880px",
    height: "100%",
    float: "right",
    backgroundColor: "#f3f6f6",
  },
  content: {
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  contentBlur: {
    filter: "blur(6px)",
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  saveSettingsButton: {
    float: "right",
  },
  restart: {
    fontWeight: "bold",
  },
  settingsSaveButton: {
    marginTop: "10px",
    marginRight: "27px",
    float: "right",
  },
  settingsRow: {
    width: "100%",
    height: "50px",
    paddingTop: "15px",
    float: "left",
    borderBottom: "1px black solid",
  },
  settingsLabel: {
    width: "50%",
    paddingLeft: "10px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "20px",
    textAlign: "left",
  },
  settingsInput: {
    width: "45%",
    paddingRight: "10px",
    float: "left",
    height: "100%",
    fontSize: "20px",
    paddingTop: "5px",
    textAlign: "right",
  },
  settingsInputSelect: {
    display: "block",
    overflow: "hidden",
    float: "right",
    color: "rgb(12, 30, 62)",
    fontSize: "19px",
  },
  settingsInputSelectOption: {
    overflow: "hidden",
    height: "34px",
    marginRight: "20px",
    paddingTop: "5px",
    paddingLeft: "10px",
    color: "rgb(41, 113, 255)",
    fontSize: "19px",
  },
  settingsInputError: {
    width: "290px",
    float: "right",
    height: "100%",
    textAlign: "left",
    color: "red",
    paddingTop: "5px",
  },
};
export const StakePoolStyles = {
  body: {
    position: "fixed",
    left: "0px",
    top: "50%",
    right: "0px",
    display: "block",
    overflow: "hidden",
    width: "1178px",
    height: "770px",
    marginTop: "-385px",
    marginRight: "auto",
    marginLeft: "auto",
    backgroundColor: "#FFF",
  },
  view: {
    width: "880px",
    height: "100%",
    float: "right",
    backgroundColor: "#f3f6f6",
  },
  viewNotificationError: {
    marginTop: "20px",
    display: "inline-block",
    marginRight: "auto",
    marginLeft: "auto",
    padding: "7px 20px 7px 7px",
    borderRadius: "5px",
    backgroundColor: "#fd714b",
    boxShadow: "0 3px 10px 0 rgba(0, 0, 0, .2)",
    color: "#fff",
    fontSize: "13px",
    textAlign: "center",
  },
  viewNotificationSuccess: {
    marginTop: "20px",
    display: "inline-block",
    marginRight: "auto",
    marginLeft: "auto",
    padding: "7px 20px 7px 7px",
    borderRadius: "5px",
    backgroundColor: "#41bf53",
    boxShadow: "0 3px 10px 0 rgba(0, 0, 0, .2)",
    color: "#fff",
    fontSize: "13px",
    textAlign: "center",
    textDecoration: "none",
  },
  contentNestAddressDeleteIcon: {
    width: "26px",
    height: "19px",
    float: "left",
    backgroundImage: `url(${Delete})`,
    backgroundPosition: "50% 50%",
    backgroundSize: "8px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      opacity: "0.85",
    }
  },
  transition1: {
    transition: "all 100ms ease-in-out",
  },
  headerMetaSend: {
    height: "54px",
    width: "480px",
    paddingLeft: "50px",
    color: "#0c1e3e",
    fontSize: "14px",
  },
  content: {
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  contentBlur: {
    filter: "blur(6px)",
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  contentVotingGui: {
    overflow: "auto",
    height: "556px",
    padding: "0px 60px 10px 80px",
  },
  contentPurchaseTicketViewBlur: {
    filter: "blur(6px)",
    overflow: "auto",
    height: "565px",
    padding: "20px 60px 20px 80px",
  },
  contentPurchaseTicketView: {
    overflow: "auto",
    height: "565px",
    padding: "20px 60px 20px 80px",
  },
  instructions: {
    fontSize: "13px",
  },
  contentNestPurchaseTicketForm: {
    width: "100%",
    height: "100%",
    paddingTop: "2px",
    paddingLeft: "10px",
    borderStyle: "none",
    color: "#2971ff",
    borderBottom: "1px solid",
    fontSize: "15px",
    cursor: "text",
    ":focus": {
      color: "#2971ff",
    },
  },
  contentNestPurchaseTicketFormDisabled: {
    width: "100%",
    height: "100%",
    paddingTop: "2px",
    paddingLeft: "10px",
    borderStyle: "none",
    color: "#2971ff",
    fontSize: "15px",
    cursor: "text",
    ":focus": {
      color: "#2971ff",
    },
  },
  contentNestSend: {
    paddingTop: "1px",
    backgroundColor: "#fff",
  },
  contentNestDeleteAddress: {
    width: "625px",
    height: "54px",
    paddingTop: "10px",
    paddingLeft: "116px",
    float: "left",
  },
  contentNestPrefixConfigured: {
    width: "200px",
    paddingRight: "15px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "19px",
    textAlign: "right",
    textTransform: "capitalize",
  },
  contentNestStakePool: {
    borderTop: "1px solid",
    height: "185px",
    position: "relative",
    borderBottom: "1px solid",
    float: "left",
  },
  contentNestBalance: {
    borderTop: "1px solid",
    height: "260px",
    position: "relative",
    borderBottom: "1px solid",
    float: "left",
  },
  contentNestStakePoolSettings: {
    width: "100%",
    height: "20px",
    marginTop: "20px",
    float: "left",
  },
  contentNestBalanceOverview: {
    width: "100%",
    height: "25px",
    marginTop: "10px",
    float: "left",
  },
  contentNestPrefixStakePoolSettings: {
    width: "125px",
    paddingRight: "15px",
    float: "left",
    height: "100%",
    fontSize: "19px",
    textAlign: "right",
    textTransform: "capitalize",
  },
  contentNestPrefixBalanceOverview: {
    width: "245px",
    paddingRight: "15px",
    float: "left",
    height: "100%",
    fontSize: "19px",
    textAlign: "right",
    textTransform: "capitalize",
  },
  contentNestStakePoolSettingsBottom: {
    width: "100%",
    height: "20px",
    marginTop: "30px",
    float: "left",
  },
  contentNestBalanceOverviewBottom: {
    width: "100%",
    height: "20px",
    marginTop: "30px",
    float: "left",
  },
  contentNestContentStakePoolSettings: {
    position: "relative",
    overflowY: "hidden",
    overflowX: "auto",
    width: "575px",
    height: "30px",
    float: "left",
    fontSize: "13px",
    paddingTop: "2px",
  },
  contentNestContentBalanceOverview: {
    position: "relative",
    overflowY: "hidden",
    overflowX: "auto",
    width: "465px",
    height: "20px",
    float: "left",
    fontSize: "13px",
    paddingTop: "2px",
  },
  contentNestPrefixSend: {
    width: "100px",
    paddingRight: "15px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "19px",
    textAlign: "right",
    textTransform: "capitalize",
  },
  stakePoolUnconfiguredSelect: {
    width: "350px",
    float: "left",
    fontSize: "16px",
    paddingLeft: "10px",
  },
  contentNestPrefixConfirm: {
    width: "230px",
    paddingRight: "15px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "19px",
    textAlign: "right",
    textTransform: "capitalize",
  },
  contentNestFromAddress: {
    width: "100%",
    height: "54px",
    paddingTop: "10px",
    float: "left",
  },
  contentNestApiKeyInstructions: {
    width: "600px",
    height: "285px",
    paddingLeft: "30px",
    float: "left",
  },
  contentNestApiKey: {
    position: "relative",
    paddingLeft: "65px",
    width: "600px",
    height: "34px",
    float: "left",
    fontSize: "13px",
  },
  contentNestToAddress: {
    width: "100%",
    height: "54px",
    paddingTop: "10px",
    float: "left",
  },
  contentNestAddressHashTo: {
    width: "100%",
    height: "100%",
    paddingTop: "4px",
    paddingLeft: "10px",
    borderStyle: "none",
    color: "#2971ff",
    fontSize: "13px",
    cursor: "text",
    ":focus": {
      color: "#2971ff",
    },
  },
  contentNestAddressHashBlock: {
    position: "relative",
    width: "600px",
    height: "34px",
    float: "left",
    fontSize: "13px",
  },
  contentNestAddressHashBlockConfirm: {
    position: "relative",
    overflow: "hidden",
    width: "300px",
    height: "34px",
    paddingTop: "7px",
    float: "left",
    fontSize: "17px",
  },
  contentNestGradient: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    width: "40px",
    height: "100%",
    backgroundImage: "linear-gradient(90deg, transparent, #fff 80%)",
  },
  selectAccountsSend: {
    width: "300px",
    position: "relative",
    zIndex: "3",
    overflow: "visible",
    height: "34px",
    minWidth: "300px",
    float: "left",
    borderBottom: "1px solid #2971ff",
    backgroundColor: "#fff",
    backgroundImage: `url(${ArrowDownMidBlue})`,
    backgroundPosition: "100% 50%",
    backgroundSize: "10px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      backgroundImage: `url(${ArrowDownKeyBlue})`,
      backgroundSize: "10px",
    }
  },
  selectAccount: {
    display: "block",
    overflow: "hidden",
    width: "100%",
    height: "100%",
    color: "#0c1e3e",
    fontSize: "19px",
    ":hover": {
      height: "auto",
    }
  },
  selectAccountNFirst: {
    overflow: "hidden",
    height: "34px",
    marginRight: "20px",
    paddingTop: "5px",
    paddingLeft: "10px",
    color: "#2971ff",
    fontSize: "19px",
  },
  selectAccountNTextSend: {
    width: "200%",
    paddingTop: "1px",
    fontSize: "13px",
  },
  selectAccountNAmount: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    marginRight: "20px",
    paddingTop: "7px",
    paddingLeft: "40px",
    backgroundImage: "linear-gradient(90deg, transparent, #fff 28%)",
    fontFamily: "Inconsolata, monospace",
    color: "#596d81",
    fontSize: "11px",
    fontWeight: "400",
    textAlign: "right",
  },
  selectAccountNAmountBold: {
    fontFamily: "Inconsolata, monospace",
    fontWeight: "700",
  },
  selectAccountNNestSend: {
    fontSize: "13px",
    overflow: "auto",
    height: "auto",
    maxHeight: "413px",
    paddingTop: "10px",
    paddingBottom: "10px",
    borderBottom: "1px solid #a9b4bf",
    backgroundColor: "#fff",
  },
  selectAccountNGradient: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    width: "40px",
    height: "100%",
    backgroundImage: "linear-gradient(90deg, transparent, #fff 75%)",
  },
  selectAccountN: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    paddingTop: "18px",
    paddingBottom: "18px",
    paddingLeft: "10px",
    float: "left",
    ":hover": {
      color: "#2971ff",
    }
  },
  selectAccountNText: {
    width: "200%",
  },
  highlightTextNeonGreen: {
    color: "#2ed8a3",
  },
  highlighTextOrange: {
    color: "#fd714b",
  },
  selectVotingPreferences: {
    display: "block",
    float: "right",
    overflow: "hidden",
    height: "100%",
    paddingTop: "3px",
    color: "#0c1e3e",
    ":hover": {
      height: "auto",
    }
  },
  selectPurchaseTickets: {
    display: "block",
    overflow: "hidden",
    height: "100%",
    width: "100%",
    paddingTop: "3px",
    color: "#0c1e3e",
    ":hover": {
      height: "auto",
    }
  },
  selectPurchaseTicketsNFirst: {
    overflow: "hidden",
    height: "34px",
    marginRight: "20px",
    paddingTop: "5px",
    paddingLeft: "10px",
    color: "#2971ff",
    fontSize: "19px",
  },
  selectPurchaseTicketsNTextSend: {
    width: "200%",
    paddingTop: "1px",
    fontSize: "13px",
  },
  selectPurchaseTicketsNAmount: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    marginRight: "20px",
    paddingTop: "7px",
    paddingLeft: "40px",
    backgroundImage: "linear-gradient(90deg, transparent, #fff 28%)",
    fontFamily: "Inconsolata, monospace",
    color: "#596d81",
    fontSize: "11px",
    fontWeight: "400",
    textAlign: "right",
  },
  selectPurchaseTicketsNAmountBold: {
    fontFamily: "Inconsolata, monospace",
    fontWeight: "700",
  },
  selectPurchaseTicketsNNestSend: {
    fontSize: "13px",
    overflow: "auto",
    height: "auto",
    maxHeight: "413px",
    paddingTop: "10px",
    paddingBottom: "10px",
    borderBottom: "1px solid #a9b4bf",
    backgroundColor: "#fff",
  },
  selectPurchaseTicketsNGradient: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    width: "40px",
    height: "100%",
    backgroundImage: "linear-gradient(90deg, transparent, #fff 75%)",
  },
  selectPurchaseTicketsN: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    paddingTop: "18px",
    paddingBottom: "18px",
    paddingLeft: "10px",
    float: "left",
    ":hover": {
      color: "#2971ff",
    }
  },
  selectPurchaseTicketsNText: {
    width: "200%",
  },
  inputForm: {
    position: "relative",
    width: "100%",
    height: "25px",
  },
  inputFormPurchaseTicket: {
    position: "relative",
    width: "100%",
    height: "25px",
    paddingTop: "1px",
  },
  contentNestAddressAmount: {
    display: "block",
    height: "34px",
    float: "right",
  },
  contentNestAddressAmountSumAndCurrency: {
    position: "relative",
    overflow: "hidden",
    width: "140px",
    height: "100%",
    marginRight: "20px",
    float: "right",
    borderBottom: "1px solid #a9b4bf",
    color: "#0c1e3e",
    textAlign: "right",
  },
  contentNestAddressAmountSumGradient: {
    position: "absolute",
    top: "0px",
    right: "0px",
    bottom: "0px",
    display: "inline-block",
    width: "37px",
    height: "100%",
    paddingTop: "9px",
    paddingRight: "10px",
    backgroundColor: "#fff",
    fontFamily: "Inconsolata, monospace",
    fontSize: "13px",
    textTransform: "uppercase",
  },
  contentNestAddressAmountSum: {
    display: "block",
    width: "100%",
    height: "100%",
    fontSize: "19px",
    fontWeight: "700",
  },
  contentNestToAddressAmountSumNumberFormatSmall: {
    fontSize: "13px",
  },
  contentNestAddressAmountSumNumberFormatSmall: {
    fontSize: "13px",
  },
  contentSend: {
    marginTop: "20px",
  },
  contentSendSection: {
    display: "block",
    width: "91%",
    height: "22px",
    paddingLeft: "30px",
    float: "left",
    color: "#0c1e3e",
  },
  contentSendSectionCheckboxText: {
    height: "100%",
    paddingTop: "1px",
    paddingLeft: "5px",
    float: "left",
    textTransform: "capitalize",
  },
  contentSendSectionAmount: {
    width: "160px",
    height: "100%",
    paddingTop: "1px",
    paddingRight: "30px",
    float: "right",
    fontFamily: "Inconsolata, monospace",
    fontSize: "13px",
    textAlign: "right",
  },
  contentSendSectionDescription: {
    height: "100%",
    paddingTop: "1px",
    paddingRight: "20px",
    float: "right",
    color: "#596d81",
    fontSize: "13px",
  },
  contentSendSectionAmountCurrency: {
    paddingLeft: "5px",
  },
  contentPurchaseButton: {
    marginTop: "8px",
    marginLeft: "8px",
    float: "left",
  },
  contentRevokeButton : {
    marginTop: "8px",
    marginRight: "8px",
    float: "right",
  },
  contentImportScriptButton: {
    marginTop: "8px",
    marginRight: "8px",
    float: "right",
  },
  showAdvanced: {
    width: "300px",
    position: "relative",
    zIndex: "3",
    overflow: "visible",
    height: "34px",
    minWidth: "300px",
    float: "left",
    borderBottom: "1px solid #2971ff",
    backgroundColor: "#fff",
    backgroundImage: `url(${ArrowDownMidBlue})`,
    backgroundPosition: "100% 50%",
    backgroundSize: "10px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      backgroundImage: `url(${ArrowDownKeyBlue})`,
      backgroundSize: "10px",
    }
  },
  hideAdvanced: {
    width: "300px",
    position: "relative",
    zIndex: "3",
    overflow: "visible",
    height: "34px",
    minWidth: "300px",
    float: "left",
    borderBottom: "1px solid #2971ff",
    backgroundColor: "#fff",
    backgroundImage: `url(${ArrowUpLightBlue})`,
    backgroundPosition: "100% 50%",
    backgroundSize: "10px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      backgroundImage: `url(${ArrowUpTurquiose})`,
      backgroundSize: "10px",
    }
  },
  selectStakePoolArea: {
    paddingTop: "4px"
  },
  autoBuyerQuickBarRow: {
    width: "400px",
    paddingLeft: "37px",
    paddingTop: "8px",
    float: "left",
    position: "relative",
  },

/*
  .switch.disabled-inactive {
    background-color: #f3f6f6;
    cursor: default;
  }

  .switch.disabled-inactive.transition0.automatic-purchase {
    float: left;
  }

  .switch.enabled-inactive {
    background-color: #f3f6f6;
    cursor: default;
  }

  .switch.enabled-inactive.transition0.automatic-purchase {
    float: left;
  }
  .switch-knob.disabled-inactive {
    float: right;
    background-color: #e7eaed;
  }

  .switch-knob.enabled-inactive {
    background-color: #e7eaed;
  }
  */

  autoBuyerLabel: {
    width: "75px",
    display: "block",
    paddingTop: "13px",
    paddingLeft: "20px",
    float: "left",
    color: "#0c1e3e",
    fontSize: "19px",
    textTransform: "capitalize",
  },
  autoBuyerShowAdvancedArea: {
    float: "right",
    paddingTop: "13px",
  },
  flexHeightAutoBuyerHidden: {
    paddingTop: "1px",
    backgroundColor: "#fff",
    height:"54px",
    width: "740px",
    float: "left",
    overflowY: "auto",
    overflowX: "hidden",
    transition: "all 100ms cubic-bezier(0.86, 0, 0.07, 1) 0s",
  },
  flexHeightAutoBuyerShown: {
    paddingTop: "1px",
    backgroundColor: "#fff",
    height:"258px",
    width: "740px",
    float: "left",
    overflowY: "auto",
    overflowX: "hidden",
  },
  autoBuyerRow: {
    width: "100%",
    height: "54px",
    float: "left",
  },
  purchaseTicketQuickBarRow: {
    height: "36px",
    float: "left",
    paddingTop: "5px",
    paddingRight: "20px",
    position: "relative",
  },
  quickBarRowLabel: {
    width: "120px",
    position: "relative",
    paddingTop: "6px",
    float: "left",
    fontSize: "13px",
    paddingRight: "10px",
    color: "#0c1e3e",
    height: "100%",
    textAlign: "right",
    textTransform: "capitalize",
  },
  autoBuyerIconAreas: {
    marginTop: "8px",
    paddingRight: "10px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "11px",
    lineHeight: "17px",
  },
  autoBuyerIconAreasExpand: {
    marginTop: "8px",
    width: "140px",
    textAlign: "right",
    paddingRight: "10px",
    paddingLeft: "10px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "11px",
    lineHeight: "17px",
  },
  balanceToMaintainIcon: {
    display: "block",
    backgroundImage: `url(${BalanceToMaintainIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    height: "16px",
    width: "16px",
    paddingRight: "10px",
    float: "left",
  },
  maxFeeIcon: {
    display: "block",
    backgroundImage: `url(${MaxFeeIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    height: "16px",
    width: "16px",
    paddingRight: "10px",
    float: "left",
  },
  maxPriceAbsoluteIcon: {
    display: "block",
    backgroundImage: `url(${MaxPriceAbsoluteIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    height: "16px",
    width: "16px",
    paddingRight: "10px",
    float: "left",
  },
  maxPriceRelativeIcon: {
    display: "block",
    backgroundImage: `url(${MaxPriceRelativeIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    height: "16px",
    width: "16px",
    paddingRight: "10px",
    float: "left",
  },
  maxPerBlockIcon: {
    display: "block",
    backgroundImage: `url(${MaxPerBlockIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    height: "16px",
    width: "16px",
    paddingRight: "10px",
    float: "left",
  },
  stakepoolIcon: {
    display: "block",
    backgroundImage: `url(${StakePoolIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    height: "16px",
    minWidth: "20px",
    marginTop: "8px",
    paddingRight: "18px",
    paddingLeft: "20px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "11px",
    lineHeight: "17px",
  },
  expiryIcon: {
    backgroundImage: `url(${ExpiryIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    display: "block",
    height: "16px",
    minWidth: "20px",
    marginTop: "8px",
    paddingRight: "18px",
    paddingLeft: "20px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "11px",
    lineHeight: "17px",
  },
  feeIcon: {
    backgroundImage: `url(${SplitFeeIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    display: "block",
    height: "16px",
    minWidth: "20px",
    marginTop: "8px",
    paddingRight: "18px",
    paddingLeft: "20px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "11px",
    lineHeight: "17px",
  },
  ticketAddressIcon: {
    backgroundImage: `url(${TicketAddressIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    display: "block",
    height: "16px",
    minWidth: "20px",
    marginTop: "8px",
    paddingRight: "18px",
    paddingLeft: "20px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "11px",
    lineHeight: "17px",
  },
  feeAddressIcon: {
    backgroundImage: `url(${FeeAddressIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    display: "block",
    height: "16px",
    minWidth: "20px",
    marginTop: "8px",
    paddingRight: "18px",
    paddingLeft: "20px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "11px",
    lineHeight: "17px",
  },
  poolFeeIcon: {
    backgroundImage: `url(${PoolFeeIcon})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "16px",
    backgroundRepeat: "no-repeat",
    display: "block",
    height: "16px",
    minWidth: "20px",
    marginTop: "8px",
    paddingRight: "18px",
    paddingLeft: "20px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    color: "#0c1e3e",
    fontSize: "11px",
    lineHeight: "17px",
  },
  stakeInfoArea: {
    paddingTop: "1px",
    backgroundColor: "rgb(255, 255, 255)",
    height: "130px",
    width: "740px",
    float: "left",
    marginBottom: "10px",
  },
  stakeInfoAreaSmall: {
    paddingTop: "1px",
    backgroundColor: "rgb(255, 255, 255)",
    height: "25px",
    width: "740px",
    float: "left",
    marginBottom: "10px",
    transition: "all 100ms cubic-bezier(0.86, 0, 0.07, 1) 0s",
  },
  stakeInfoRowSmall: {
    width: "33%",
    float: "left",
  },
  stakeInfoRowSmallRight: {
    width: "34%",
    float: "left",
  },
  stakeInfoRow: {
    width: "100%",
    height: "25px",
    float: "left",
    borderBottom: "1px #E7EAED solid",
  },
  stakeInfoRowLeft: {
    width: "50%",
    float: "left",
  },
  stakeInfoRowRight: {
    width: "50%",
    float: "right",
  },
  stakeInfoLabel: {
    width: "152px",
    paddingRight: "15px",
    paddingLeft: "5px",
    float: "left",
    height: "100%",
    paddingTop: "2px",
    fontSize: "14px",
    textAlign: "right",
  },
  stakeInfoValue: {
    fontFamily: "Inconsolata, monospace",
    float: "left",
    paddingTop: "3px",
  },
  purchaseTicketRow: {
    width: "100%",
    height: "45px",
    paddingTop: "2px",
    float: "left",
    borderBottom: "1px #E7EAED solid",
  },
  purchaseTicketRowThirds: {
    width: "33%",
    float: "left",
  },
  purchaseTicketRowAccountSelect: {
    width: "58%",
    float: "left",
  },
  purchaseTicketAccountSelectLabel: {
    width: "86px",
    paddingRight: "15px",
    paddingLeft: "5px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "16px",
    textAlign: "right",
  },
  purchaseTicketRowNumTickets: {
    width: "42%",
    float: "left",
  },
  purchaseTicketRowLeft: {
    width: "50%",
    float: "left",
  },
  purchaseTicketRowRight: {
    width: "50%",
    float: "right",
  },
  purchaseTicketLabel: {
    width: "152px",
    paddingRight: "15px",
    paddingLeft: "5px",
    float: "left",
    height: "100%",
    paddingTop: "5px",
    fontSize: "16px",
    textAlign: "right",
  },
  purchaseTicketInput: {
    width: "283px",
    float: "left",
    height: "100%",
    fontSize: "19px",
    textAlign: "right",
  },
  purchaseTicketInputSelect: {
    width: "283px",
    float: "left",
    height: "100%",
    fontSize: "16px",
    textAlign: "left",
  },
  purchaseTicketNumSelect: {
    width: "85px",
    float: "left",
    height: "100%",
    fontSize: "19px",
    textAlign: "right",
  },
  purchaseTicketNumInput: {
    width: "146px",
    float: "left",
    height: "100%",
    fontSize: "19px",
    textAlign: "right",
  },
  purchaseTicketThirdsInput: {
    width: "53px",
    float: "left",
    height: "100%",
    fontSize: "19px",
    textAlign: "right",
  },
  purchaseTicketAddressInput: {
    width: "331px",
    float: "left",
    height: "100%",
    fontSize: "19px",
    textAlign: "right",
  },
  purchaseTicketInputButtons: {
    width: "90px",
    float: "right",
    paddingTop: "5px",
    paddingLeft: "10px",
  },
  managePoolButtonArea: {
    float: "left",
    paddingTop: "8px",
    paddingLeft: "10px",
  },
  purchaseTicketInputError: {
    float: "right",
    width: "200px",
    textAlign: "left",
    color: "red",
    fontSize: "11px",
    paddingTop: "4px",
  },
  areaSpacing: {
    float: "left",
    height: "25px",
    width: "100%",
  },
  apiKeyError: {
    paddingLeft: "70px",
    textAlign: "left",
    float: "left",
    color: "red",
  },
  stakepoolLink: {
    color: "#2971ff",
    fontWeight: "bold",
    cursor: "pointer",
  },
  flexHeight: {
    backgroundColor: "#fff",
    float: "left",
  },
  flexHeightBalanceOverview: {
    paddingTop: "1px",
    backgroundColor: "#fff",
    height:"553px",
    float: "left",
    overflowY: "auto",
    overflowX: "hidden",
  },
  flexHeightHidden: {
    paddingTop: "1px",
    backgroundColor: "#fff",
    height:"116px",
    width: "740px",
    float: "left",
    overflowY: "auto",
    overflowX: "hidden",
    transition: "all 100ms cubic-bezier(0.86, 0, 0.07, 1) 0s",
  },
  purchaseTicketButtonsArea: {
    width: "740px",
    float: "left",
  },
  flexHeightShown: {
    paddingTop: "1px",
    backgroundColor: "#fff",
    height:"288px",
    width: "740px",
    float: "left",
    overflowY: "auto",
    overflowX: "hidden",
  },
  loading: {
    marginTop: "110px",
    marginLeft: "268px",
  },
  selectAccountsPurchase: {
    width: "300px",
    position: "relative",
    zIndex: "3",
    overflow: "visible",
    height: "34px",
    minWidth: "300px",
    float: "left",
    borderBottom: "1px solid #2971ff",
    backgroundColor: "#fff",
    backgroundImage: `url(${ArrowDownMidBlue})`,
    backgroundPosition: "100% 50%",
    backgroundSize: "10px",
    backgroundRepeat: "no-repeat",
    cursor: "pointer",
    ":hover": {
      backgroundImage: `url(${ArrowDownKeyBlue})`,
      backgroundSize: "10px",
    }
  },
  toggle: {
    fontFamily: "Source Sans Pro, sans-serif",
    float: "right",
  },
  contentTitle: {
    display: "block",
    height: "44px",
    marginRight: "auto",
    marginBottom: "10px",
    marginLeft: "auto",
    borderBottom: "1px solid transparent",
    color: "#596d81",
    fontSize: "27px",
  },
  contentTitleText: {
    display: "inline-block",
    overflow: "hidden",
    width: "500px",
    height: "100%",
    paddingTop: "13px",
    paddingRight: "20px",
    paddingLeft: "20px",
  },
  votingTitleArea: {
    display: "block",
    height: "20px",
    width: "740px",
    borderBottom: "1px solid transparent",
    color: "#596d81",
    fontSize: "20px",
  },
  votingTitleAreaName: {
    fontSize: "20px",
    display: "inline-block",
    height: "100%",
    paddingTop: "10px",
    paddingBottom: "10px",
    float: "left",
  },
  votingAgendaArea: {
    width: "100%",
    float: "left",
  },
  noAgendasMessage: {
    fontSize: "25px",
    paddingTop: "200px",
    paddingLeft: "150px",
  },
  hideStakePoolConfig: {
    float: "right",
    marginTop: "10px",
  },
  manageStakePoolsButton: {
    width: "150px",
    padding: "7px 18px",
    display: "block",
  }
};
export const HelpStyles = {
  body: {
    position: "fixed",
    left: "0px",
    top: "50%",
    right: "0px",
    display: "block",
    overflow: "hidden",
    width: "1178px",
    height: "770px",
    marginTop: "-385px",
    marginRight: "auto",
    marginLeft: "auto",
    backgroundColor: "#FFF",
  },
  view: {
    width: "880px",
    height: "100%",
    float: "right",
    backgroundColor: "#f3f6f6",
  },
  content: {
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  img: {
    width: "250px",
    paddingLeft: "244px",
  },
  center: {
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
  }
};
export const TxDetailsStyles = {
  view: {
    width: "880px",
    height: "100%",
    float: "right",
    backgroundColor: "#f3f6f6",
  },
  header: {
    paddingRight: "80px",
    paddingLeft: "100px",
    backgroundColor: "#fff",
  },
  content: {
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  headerTop: {
    height: "106px",
    paddingBottom: "20px",
  },
  headerTitleOverview: {
    height: "54px",
    paddingTop: "13px",
    color: "#596d81",
    fontSize: "27px",
  },
  headerMetaOverview: {
    height: "54px",
    paddingTop: "5px",
    fontFamily: "Inconsolata, monospace",
    fontSize: "53px",
  },
  contentTitle: {
    display: "block",
    height: "44px",
    marginRight: "auto",
    marginBottom: "10px",
    marginLeft: "auto",
    borderBottom: "1px solid transparent",
    color: "#596d81",
    fontSize: "27px",
  },
  contentNest: {
    paddingTop: "1px",
  },
  indicatorPending: {
    display: "inline-block",
    padding: "5px 8px 5px 20px",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "3px",
    fontSize: "12px",
    lineHeight: "8px",
    textAlign: "right",
    textTransform: "capitalize",
    borderColor: "#2971ff",
    backgroundImage: `url(${IndicatorPending})`,
    backgroundPosition: "6px 50%",
    backgroundSize: "10px",
    backgroundRepeat: "no-repeat",
    color: "#2971ff",
  },

  indicatorConfirmed: {
    display: "inline-block",
    padding: "5px 8px 5px 20px",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "3px",
    fontSize: "12px",
    lineHeight: "8px",
    textAlign: "right",
    textTransform: "capitalize",
    borderColor: "#2ed8a3",
    backgroundImage: `url(${IndicatorConfirmed})`,
    backgroundPosition: "6px 50%",
    backgroundSize: "10px",
    backgroundRepeat: "no-repeat",
    color: "#2ed8a3",
  },
  headerTopTransactionDetails: {
    height: "106px",
    paddingTop: "43px",
    textAlign: "center",
    marginRight: "-20px",
  },
  headerMetaTransactionDetailsStakeTx: {
    height: "38px",
    paddingTop: "16px",
    paddingLeft: "50px",
    backgroundImage: `url(${TicketSmall})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "30px",
    backgroundRepeat: "no-repeat",
    fontFamily: "Inconsolata, monospace",
    fontSize: "35px",
    fontWeight: "700",
  },
  headerMetaTransactionDetailsIn: {
    height: "38px",
    paddingTop: "16px",
    paddingLeft: "50px",
    backgroundImage: `url(${PlusBig})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "30px",
    backgroundRepeat: "no-repeat",
    fontFamily: "Inconsolata, monospace",
    fontSize: "35px",
    fontWeight: "700",
  },
  headerMetaTransactionDetailsTransfer: {
    height: "38px",
    paddingTop: "16px",
    paddingLeft: "50px",
    backgroundImage: `url(${WalletGray})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "30px",
    backgroundRepeat: "no-repeat",
    fontFamily: "Inconsolata, monospace",
    fontSize: "35px",
    fontWeight: "700",
  },
  headerMetaTransactionDetailsCurrency: {
    fontSize: "19px",
    fontWeight: "400",
  },

  headerMetaTransactionDetailsTimeAndDate: {
    display: "inline-block",
    paddingTop: "4px",
    float: "right",
    fontFamily: "Source Sans Pro, sans-serif",
    fontSize: "19px",
    fontWeight: "400",
  },

  headerMetaTransactionDetailsOut: {
    height: "38px",
    paddingTop: "16px",
    paddingLeft: "50px",
    backgroundImage: `url(${MinusBig})`,
    backgroundPosition: "0px 50%",
    backgroundSize: "30px",
    backgroundRepeat: "no-repeat",
    fontFamily: "Inconsolata, monospace",
    fontSize: "35px",
    fontWeight: "700",
  },

  transactionDetails: {
    paddingTop: "18px",
    paddingBottom: "8px",
    borderBottom: "1px solid #e7eaed",
    fontSize: "13px",
    height: "100px",
  },

  transactionDetailsTop: {
    paddingTop: "18px",
    paddingBottom: "8px",
    borderBottom: "1px solid #e7eaed",
    fontSize: "13px",
    height: "240px",
  },

  transactionDetailsLeft: {
    width: "150px",
    float: "left",
  },

  transactionDetailsRight: {
    width: "570px",
    float: "right",
  },

  transactionDetailsName: {
    display: "block",
    width: "160px",
    height: "28px",
    paddingTop: "4px",
    paddingRight: "20px",
    float: "left",
    clear: "left",
    fontSize: "13px",
    lineHeight: "19px",
    textAlign: "right",
  },
  transactionDetailsOverview: {
    height: "100px",
    width: "100%",
    paddingLeft: "80px",
  },
  transactionDetailsOverviewTitle: {
    float: "left",
    height: "30px",
    width: "100%",
    fontSize: "20px",
    fontWeight: "700",
    borderTop: "1px solid #e7eaed",
    paddingTop: "10px",
  },
  transactionDetailsOverviewTitleCreated: {
    float: "right",
    width: "63%",
  },
  transactionDetailsOverviewTitleConsumed: {
    float: "left",
    width: "30%",
  },
  transactionDetailsInputArea: {
    float: "left",
    width: "30%",
    height: "100px",
    overflow: "auto",
    backgroundImage: `url(${ArrowRightKeyBlue})`,
    backgroundPosition: "100% 50%",
    backgroundSize: "15px",
    backgroundRepeat: "no-repeat",
    paddingRight: "35px",
  },
  transactionDetailsOutputArea: {
    float: "right",
    width: "56%",
    height: "100px",
    overflow: "auto",
    paddingRight: "50px",
  },
  transactionDetailsDirection: {
    display: "block",
    width: "100%",
    height: "28px",
    paddingTop: "4px",
    paddingLeft: "80px",
    float: "left",
    clear: "left",
    fontSize: "20px",
    lineHeight: "19px",
    textAlign: "left",
  },
  transactionDetailsValue: {
    display: "inline-block",
    height: "28px",
    paddingTop: "9px",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    lineHeight: "10px",
    fontWeight: "700",
    textAlign: "left",
  },
  transactionDetailsRow: {
    display: "inline-block",
    height: "28px",
    paddingTop: "9px",
    width: "100%",
    float: "left",
    fontFamily: "Inconsolata, monospace",
    lineHeight: "10px",
    fontWeight: "700",
  },
  transactionDetailsAddress: {
    width: "50%",
    float: "left",
    textAlign: "left",
  },
  transactionDetailsAmount: {
    width: "50%",
    float: "right",
    textAlign: "right",
  },

  transactionDetailsValueText: {
    fontWeight: "400",
  },

  transactionDetailsTitle: {
    width: "140px",
    height: "28px",
    paddingTop: "4px",
    color: "#596d81",
    fontSize: "20px",
    textAlign: "right",
  },

  transactionDetailsLast: {
    borderBottom: "0px none transparent",
  }
};
export const GetStartedStyles = {
  toggle: {
    fontFamily: "Source Sans Pro, sans-serif",
    float: "right",
  },
  body: {
    position: "fixed",
    left: "0px",
    top: "50%",
    right: "0px",
    display: "block",
    overflow: "hidden",
    width: "1178px",
    height: "770px",
    marginTop: "-385px",
    marginRight: "auto",
    marginLeft: "auto",
    backgroundColor: "#FFF",
  },
  view: {
    width: "880px",
    height: "100%",
    float: "right",
    backgroundColor: "#0c1e3e",
  },
  content: {
    overflow: "auto",
    height: "556px",
    padding: "54px 60px 54px 80px",
  },
  contentTitle: {
    display: "block",
    height: "44px",
    marginRight: "auto",
    marginBottom: "10px",
    marginLeft: "auto",
    borderBottom: "1px solid transparent",
    color: "#596d81",
    fontSize: "27px",
  },
  fetchHeadersMessage: {
    fontSize: "25px",
    color: "#c4cbd2",
  },
  contentNest: {
    paddingTop: "1px",
  },
  contentTitleText: {
    display: "inline-block",
    overflow: "hidden",
    width: "600px",
    height: "100%",
    paddingTop: "13px",
    paddingRight: "20px",
    paddingLeft: "20px",
    float: "left",
  },
  privPassError: {
    width: "290px",
    paddingLeft: "214px",
    height: "100%",
    textAlign: "left",
    color: "red",
    paddingTop: "17px",
  },
  contentTitleButtonSearchTransition1: {
    width: "60px",
    height: "100%",
    cursor: "pointer",
  },

  contentTitleTextActive: {
    color: "#2971ff",
  },

  contentTitleActive: {
    borderBottom: "1px solid #2971ff",
  },
  rpcRetryMessage: {
    color: "#c4cbd2",
    float: "left",
    width: "525px",
    paddingTop: "20px",
    fontSize: "25px",
  },
  rpcRetryButton: {
    width: "100px",
    marginTop: "10px",
    float: "right",
  },
  headerMetaCurrency: {
    fontSize: "23px",
  },
  viewButtonGoBack: {
    marginRight: "80px",
    marginBottom: "20px",
  },
  viewButtonKeyBlueWalletNewSeed: {
    float: "left",
  },
  contentNewSeed: {
    overflow: "auto",
    height: "556px",
    padding: "54px 80px 54px 80px",
  },
  contentNewSeedPrivPass: {
    paddingTop: "10px",
    height: "80px",
  },
  contentConfirmWalletCreateInputLeft: {
    width: "187px",
    marginRight: "20px",
    float: "left",
    color: "#E7EAED",
    fontSize: "19px",
    textAlign: "right",
    letterSpacing: "-0.1px",
  },
  contentConfirmWalletCreateInputLeftPadding: {
    width: "187px",
    marginRight: "20px",
    float: "left",
    color: "#E7EAED",
    fontSize: "19px",
    textAlign: "right",
    letterSpacing: "-0.1px",
    paddingTop: "23px",
  },
  contentConfirmWalletCreateInputRight: {
    width: "540px",
    float: "left",
    clear: "right",
  },
  contentConfirmWalletCreateInputRightPadding: {
    marginBottom: "5px",
    width: "300px",
    paddingTop: "11px",
    float: "left",
    clear: "right",
  },
  inputPrivatePassword: {
    backgroundColor: "transparent",
    width: "100%",
    minHeight: "44px",
    paddingRight: "10px",
    paddingLeft: "10px",
    borderStyle: "none none solid",
    borderBottom: "1px solid #69D5F7",
    color: "#69D5F7",
    fontSize: "19px",
    lineHeight: "normal",
    margin: "0px",
    boxSizing: "border-box",
  },
  inputForm: {
    MozAppearance: "none !important",
    position: "relative",
    width: "100%",
    height: "auto",
    minHeight: "44px",
  },
  inputFormError: {
    color: "red",
  },
  contentNewSeedCreateButton: {
    height: "80px",
    float: "left",
  },
  loading: {
    marginTop: "110px",
    marginLeft: "268px",
  },
  linearLoading: {
    backgroundColor: "white",
  },
  viewNotificationError: {
    marginTop: "20px",
    display: "inline-block",
    marginRight: "auto",
    marginLeft: "auto",
    padding: "7px 20px",
    borderRadius: "5px",
    backgroundColor: "#fd714b",
    boxShadow: "0 3px 10px 0 rgba(0, 0, 0, .2)",
    color: "#fff",
    fontSize: "13px",
    textAlign: "center",
  },
  viewNotificationSuccess: {
    marginTop: "20px",
    display: "inline-block",
    marginRight: "auto",
    marginLeft: "auto",
    padding: "7px 20px",
    borderRadius: "5px",
    backgroundColor: "#41bf53",
    boxShadow: "0 3px 10px 0 rgba(0, 0, 0, .2)",
    color: "#fff",
    fontSize: "13px",
    textAlign: "center",
    textDecoration: "none",
  },
};
